# Catenary 插件配置檔案

general:
  # 是否啟用除錯模式
  debugMode: false
  
  # 每個玩家可建立的最大結構數量
  maxStructuresPerPlayer: 50
  
rendering:
  # 結構的可見距離 (方塊)
  viewDistance: 64
  
  # 更新間隔 (刻)
  updateInterval: 20

permissions:
  # 是否檢查權限
  checkPermissions: true
